class Robot:
    def preMount(self, puck_pos, pin_pos, samp_id):
        ...

    def mount(self, puck_pos, pin_pos, samp_id):
        ...

    def postMount(self, puck_pos, pin_pos, samp_id):
        ...

    def unmount(self, puck_pos, pin_pos, abs_pos):
        ...
